apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: appname
deploy:
  kubectl:
    defaultNamespace: appname
build:
  local:
    push: false
  artifacts:
    - image: repo/appname-auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: repo/appname-online
      context: online
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
