apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-online-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname-online
  template:
    metadata:
      labels:
        app: appname-online
    spec:
      containers:
        - name: appname-online
          image: repo/appname-online
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://appname-nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: appname
            - name: MONGO_URI
              value: "mongodb://appname-online-mongo-srv:27017/online"
            # - name: JWT_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: jwt-secret
            #       key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: appname-online-srv
spec:
  selector:
    app: appname-online
  ports:
    - name: appname-online
      port: 3000
      protocol: TCP
      targetPort: 3000
