apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-online-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appname-online-mongo
  template:
    metadata:
      labels:
        app: appname-online-mongo
    spec:
      containers:
        - name: appname-online-mongo
          image: mongo
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: appname-online-mongo-srv
spec:
  selector:
    app: appname-online-mongo
  ports:
    - name: appname-online-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
